name: Scraping rentals from bostad.blocket.se

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run scraper
      run: python scraper.py
    - uses: actions/upload-artifact@v3
      with:
        name: Scraped-data
        path: data.json
